using System.Text;
using WebShield.Core.Models;

namespace WebShield.Reporting;

public static class MarkdownReportWriter
{
    public static string Write(ScanResult result)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# WebShield Security Report");
        builder.AppendLine();
        builder.AppendLine($"**Target:** `{result.Target}`  ");
        builder.AppendLine($"**Started At:** `{result.StartedAt:u}`  ");
        builder.AppendLine($"**Finished At:** `{result.FinishedAt:u}`  ");
        builder.AppendLine($"**Score:** `{result.Score}/100`");
        builder.AppendLine();

        builder.AppendLine("## Summary");
        builder.AppendLine();
        foreach (var group in result.Findings.GroupBy(f => f.Severity).OrderByDescending(g => g.Key))
        {
            builder.AppendLine($"- **{group.Key}:** {group.Count()}");
        }

        builder.AppendLine();
        builder.AppendLine("## Findings");
        builder.AppendLine();

        foreach (var finding in result.Findings.OrderByDescending(f => f.Severity).ThenBy(f => f.Title))
        {
            builder.AppendLine($"### [{finding.Severity}] {finding.Title}");
            builder.AppendLine();
            builder.AppendLine($"**Check ID:** `{finding.CheckId}`");
            builder.AppendLine();
            builder.AppendLine($"**Description:** {finding.Description}");
            builder.AppendLine();
            builder.AppendLine($"**Impact:** {finding.Impact}");
            builder.AppendLine();
            builder.AppendLine($"**Recommendation:** {finding.Recommendation}");
            builder.AppendLine();
            builder.AppendLine($"**Evidence:** `{finding.Evidence}`");
            builder.AppendLine();
        }

        builder.AppendLine("## Disclaimer");
        builder.AppendLine();
        builder.AppendLine("This report is generated by a defensive scanner. It is not a full penetration test and should be combined with manual review, threat modeling, and secure code review.");

        return builder.ToString();
    }
}
